# Generated by Django 3.0.3 on 2020-06-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_usersanswer_quiz_taker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizTaker',
        ),
    ]
